#!/bin/bash
set -e

BASE_BRANCH="${BASE_BRANCH:-main}"
RUN_ID="${GITHUB_RUN_ID:-manual}"
BRANCH_NAME="agent/run-${RUN_ID}"

echo "Cloning repository..."
git clone "$REPO_URL" /workspace
cd /workspace

echo "Creating working branch ${BRANCH_NAME} from ${BASE_BRANCH}..."
git checkout -B "$BRANCH_NAME" "origin/${BASE_BRANCH}" || git checkout -B "$BRANCH_NAME"

git config user.email "agent@yourdomain.com"
git config user.name "Claude Agent"

echo "Reading task and system prompt..."
TASK=$(cat task.md)

if [ -f "Claude.md" ]; then
  SYSTEM_PROMPT=$(cat Claude.md)
elif [ -f "CLAUDE.md" ]; then
  SYSTEM_PROMPT=$(cat CLAUDE.md)
else
  echo "Error: neither Claude.md nor CLAUDE.md was found in repository root."
  exit 1
fi

echo "Running Claude agent..."
claude -p "$TASK" \
  --allowedTools "Read,Edit,Write,Bash(git add *),Bash(git commit *),Bash(git status *),Bash(git diff *),Bash(git log *),Bash(ls *),Bash(find *),Bash(cat *),Bash(dotnet *),Bash(npm *),Bash(npx *),Bash(mkdir *),Bash(cp *),Bash(mv *)" \
  --append-system-prompt "$SYSTEM_PROMPT" \
  --output-format json

echo "Collecting change summary..."
CHANGED_FILES=$(git status --porcelain | awk '{print $2}' | sed '/^$/d' | sort -u)
CHANGED_COUNT=$(echo "$CHANGED_FILES" | sed '/^$/d' | wc -l | tr -d ' ')

echo "Changed files count: ${CHANGED_COUNT}"
if [ "$CHANGED_COUNT" -gt 0 ]; then
  echo "Changed files:"
  echo "$CHANGED_FILES" | sed 's/^/- /'
  echo "Diff stats:"
  git diff --stat
else
  echo "No file changes produced by agent. Exiting without commit/push/PR."
  exit 0
fi

echo "Committing changes..."
git add -A
git commit -m "feat(agent): apply task updates (run ${RUN_ID})"

echo "Pushing branch ${BRANCH_NAME}..."
git push "$REPO_URL" "HEAD:${BRANCH_NAME}" --force-with-lease

if [ -z "$GH_PAT" ] || [ -z "$GITHUB_REPOSITORY" ]; then
  echo "GH_PAT or GITHUB_REPOSITORY missing. Skipping PR creation."
  exit 0
fi

OWNER="${GITHUB_REPOSITORY%%/*}"
HEAD_REF="${OWNER}:${BRANCH_NAME}"
HEAD_REF_ENCODED=$(printf '%s' "$HEAD_REF" | jq -sRr @uri)

echo "Checking for existing open PR for ${HEAD_REF}..."
EXISTING_PR=$(curl -fsSL \
  -H "Authorization: token ${GH_PAT}" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls?state=open&head=${HEAD_REF_ENCODED}" | jq -r '.[0].html_url // empty')

if [ -n "$EXISTING_PR" ]; then
  echo "PR already exists: ${EXISTING_PR}"
  echo "Done."
  exit 0
fi

echo "Creating pull request..."
PR_PAYLOAD=$(jq -n \
  --arg title "Agent update (run ${RUN_ID})" \
  --arg head "$BRANCH_NAME" \
  --arg base "$BASE_BRANCH" \
  --arg body "Automated changes generated by Claude agent.\n\n- Run ID: ${RUN_ID}\n- Changed files: ${CHANGED_COUNT}" \
  '{title: $title, head: $head, base: $base, body: $body}')

PR_URL=$(curl -fsSL \
  -X POST \
  -H "Authorization: token ${GH_PAT}" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls" \
  -d "$PR_PAYLOAD" | jq -r '.html_url // empty')

if [ -n "$PR_URL" ]; then
  echo "Created PR: ${PR_URL}"
else
  echo "PR creation call completed but no URL was returned."
fi

echo "Done."
